# Generated by Django 4.2.4 on 2023-08-08 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_tantargy_kovetelmeny'),
    ]

    operations = [
        migrations.AddField(
            model_name='kovetelmeny',
            name='felhasznalo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kovetelmenyek', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
