# Generated by Django 4.2.4 on 2023-08-08 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kovetelmeny_felhasznalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kovetelmeny',
            name='hatarido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
